-- MySQL Script generated by MySQL Workbench
-- Tue May  3 21:17:43 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema OFIC JOSE
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema OFIC JOSE
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OFIC JOSE` DEFAULT CHARACTER SET utf8 ;
USE `OFIC JOSE` ;

-- -----------------------------------------------------
-- Table `OFIC JOSE`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OFIC JOSE`.`CLIENTE` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `telefone` VARCHAR(12) NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `IDCLIENTE_UNIQUE` (`idCliente` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OFIC JOSE`.`VEICULO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OFIC JOSE`.`VEICULO` (
  `idVeiculo` INT NOT NULL AUTO_INCREMENT,
  `fabricante` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `modelo` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `anoFabr` VARCHAR(4) NOT NULL,
   `cor_01` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `cor_02` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL,
  PRIMARY KEY (`idVeiculo`),
  UNIQUE INDEX `idVeiculo_UNIQUE` (`idVeiculo` ASC),
  CONSTRAINT `idVeiculo`
    FOREIGN KEY (`idVeiculo`)
    REFERENCES `OFIC JOSE`.`CLIENTE` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
